# Generated by Django 3.0.5 on 2020-04-03 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20200403_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registers.Departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'codigo')},
        ),
    ]
